In [1]:
# NUMPY là thư viện kiểu list 
# vì 
#+ numpy nhanh
#+ có nhiều hàm tích hợp để sự dụng cho AI

#để sử sụng numpy thì: pip install numpy
import numpy as np


In [2]:
#thử tạo1 list
python_list = [1,2,3]
# chuyển đổi danh sách thành numpy list

numpy_list = np.array(python_list)
type(numpy_list)


numpy.ndarray

In [3]:
# list trong python có thể hỗ trợ nhiều loại dữ liệu trong list
my_list = [1,'chào',True, 2.0]

In [4]:
my_list = [1,2,3,4.5]
np_list = np.array(my_list)
np_list 

array([1. , 2. , 3. , 4.5])

In [5]:
#chuyển đổi kiểu duữ liệu thì sao

np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [6]:
#accessing và indexing
x = np.array([1,2,3,4,5,6,7,8]) # x= np.array(range(1,9))

In [7]:
# lấy só 4
x[3]

np.int64(4)

In [8]:
# lấy nhiều hơn 1 phân tử
# công thức [start.and.step]
# lấy 1 2 3
x[0:3]

array([1, 2, 3])

In [9]:
#lấy từ 3 - 8 theo 3 cách
#C1 
x[2:8]

array([3, 4, 5, 6, 7, 8])

In [10]:
#C2
x[2:]

array([3, 4, 5, 6, 7, 8])

In [11]:
#lấy 3 và 5
x[2],x[4]


(np.int64(3), np.int64(5))

In [12]:
#đặt danh sách index muốn truy cập

x[[2,4]]

array([3, 5])

In [13]:
data = [[1,2],[3,4],[5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
#lấy số 2
np_list[0,1]

np.int64(2)

In [15]:
#lấy số 6
np_list[2,1]

np.int64(6)

In [16]:
#lấy [3,4],[5,6]
#C1
np_list[1:,:]

array([[3, 4],
       [5, 6]])

In [17]:
#C2
np_list[[1,2],:]

array([[3, 4],
       [5, 6]])

In [18]:
#C3
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [19]:
#lấy 1 3 5
np_list[:,0]

array([1, 3, 5])

In [20]:
#lấy 1  5
#C1
np_list[[0,2],0]

array([1, 5])

In [21]:
#c2
np_list[0::2,0]

array([1, 5])

In [22]:
x=[
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
#lấy 2 6 10 14
np_list[:,1]

array([ 2,  6, 10, 14])

In [24]:
#lấy 7 11
np_list[1:3,2]

array([ 7, 11])

In [25]:
#lấy 4 7 10
np_list[[0,1,2],[3,2,1]]

array([ 4,  7, 10])

In [26]:
#lấy 16 15 14 13
np_list[3,::-1]

array([16, 15, 14, 13])

In [27]:
np_list[[3,3,3,3],[3,2,1,0]]


array([16, 15, 14, 13])

In [28]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np_x[np_x%2==0]

array([0, 2, 4, 6, 8])

In [30]:
np_x%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [31]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
idx = [ True, True,  True, False,  True, False,  True, False,  True,
       False]
np_x[idx]

array([0, 1, 2, 4, 6, 8])

In [33]:
cond1 = np_x % 2!=0
cond2 = np_x < 5
cond3 = np_x >0
np_x[cond1&cond2|cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
#BTVN thú vị 
# cho ma trận = [[99,99,99],
#                [99,99,99],
#                [99,99,99]]
# hãy tưởng tượng ô 99 trống
#giả sử 1 là x
#giả sử 0 là o

#lấy đầu vào từ phía x và phía 0 luân phiên
# Nếu đầu vào từ phía x là (0,0)

#ma trân sẽ trở thành
# [[99,99,99],
# [99,99,99],
#[99,99,99]]

#nếu đầu vào từ phía o cũng là (0,0)
#thông báo cho họ nhập lại
#nếu không thì điền vào ma trận

#thử thách: nếu người đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi

In [35]:
import numpy as np

board = np.full((3, 3), 99)
def print_board():
    print(board)
    print()
def check_win(player):
    # kiểm tra hàng
    for i in range(3):
        if np.all(board[i, :] == player):
            return True

    # kiểm tra cột
    for i in range(3):
        if np.all(board[:, i] == player):
            return True

    # kiểm tra chéo
    if np.all(np.diag(board) == player):
        return True

    if np.all(np.diag(np.fliplr(board)) == player):
        return True

    return False
current_player = 1  

while True:
    print_board()

    if current_player == 1:
        print("Lượt của X")
    else:
        print("Lượt của O")

    row = int(input("Nhập dòng (0-2): "))
    col = int(input("Nhập cột (0-2): "))

    # kiểm tra ô trống
    if board[row, col] != 99:
        print("Ô này đã được đánh, nhập lại!")
        continue

    # điền vào ma trận
    board[row, col] = current_player

    # kiểm tra thắng
    if check_win(current_player):
        print_board()
        print("X thắng!" if current_player == 1 else "O thắng!")
        break

    # đổi lượt
    current_player = 0 if current_player == 1 else 1



[[99 99 99]
 [99 99 99]
 [99 99 99]]

Lượt của X


ValueError: invalid literal for int() with base 10: ''

In [ ]:
#BTVN 2
#y = [[1,2,3],
#     [4,5,6],
#     [7,8,9]]
#lấy 4 5 6
#lấy 2 5 
#lấy 3 4 
#lấy 9 6 3

In [37]:
import numpy as np
y = [[1,2,3],
     [4,5,6],
     [7,8,9]]
list2 = np.array(y)
list2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
list2[1]


array([4, 5, 6])

In [39]:
list2[[0,1],1]

array([2, 5])

In [40]:
list2[[0,1],[2,0]]

array([3, 4])

In [41]:
list2[::-1,2]

array([9, 6, 3])

In [ ]:
#BTVN 3
#cho x = [1,2,3,4,5,6,7,8,9,10]
# 1.Xuất ra các giá trị chẵn sử dụng if
# 2.Xuất ra các  giá trị chẵn sử dụng list cpmprehension

In [42]:
x = [1,2,3,4,5,6,7,8,9,10]
list3 = np.array(x)
list3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
#1
for i in x:
    if i%2==0:
        print(i)


2
4
6
8
10


In [46]:
#2
np_x[np_x%2==0]

array([0, 2, 4, 6, 8])

In [ ]:
#BTVN
# tạo một mảng numpy có kích thước 150 x 5 . Giả sử mảng này chứa 150 mẫu dữ 
# liệu của sinh viên bao gồm chiều cao, cân nặng, tuổi, lương và điểm trung bình 
# Tách mảng dựa trên 4 cột đầu tiên thành một biến có tên là X và 
# cột cuối cùng thành y
# tách X thành X_train và X_test trong đó X_train chứa 70% dữ liệu và tách y
# thành Y_train và Y_test, trong đó Y_train chứ 70% dữ liệu 
# Tạo 10 tập dữ liệu X_train không chông chéo nhau

In [51]:
data = np.random.rand(150, 5)
data

array([[0.45527071, 0.37045299, 0.05366252, 0.34846423, 0.06044776],
       [0.65964803, 0.03495035, 0.79761661, 0.51118292, 0.16608517],
       [0.46513476, 0.70792803, 0.08184536, 0.27312753, 0.14012241],
       [0.61904487, 0.20865846, 0.57787528, 0.47144522, 0.99745636],
       [0.67912254, 0.94414121, 0.41067893, 0.79072892, 0.32043724],
       [0.68736667, 0.93316565, 0.31130649, 0.98759566, 0.70249262],
       [0.12728511, 0.63082022, 0.27968435, 0.15170706, 0.50160136],
       [0.75656545, 0.36671712, 0.48470484, 0.77063809, 0.44907924],
       [0.5664136 , 0.94958911, 0.24881782, 0.86153044, 0.59362748],
       [0.86952874, 0.84794637, 0.19375415, 0.53742626, 0.38541508],
       [0.19211989, 0.97153781, 0.77642878, 0.10081316, 0.90246053],
       [0.00119463, 0.1644444 , 0.58747493, 0.2193562 , 0.8042335 ],
       [0.94050157, 0.75609768, 0.49463837, 0.5539609 , 0.09882628],
       [0.00531412, 0.36728239, 0.56196986, 0.83299955, 0.02808579],
       [0.92010958, 0.47535895, 0.

In [53]:
X = data[:, :4]
y = data[:, 4]

In [55]:
n_train = int(0.7 * len(X))
n_train


105

In [57]:
X_train = X[:n_train]
X_train


array([[0.45527071, 0.37045299, 0.05366252, 0.34846423],
       [0.65964803, 0.03495035, 0.79761661, 0.51118292],
       [0.46513476, 0.70792803, 0.08184536, 0.27312753],
       [0.61904487, 0.20865846, 0.57787528, 0.47144522],
       [0.67912254, 0.94414121, 0.41067893, 0.79072892],
       [0.68736667, 0.93316565, 0.31130649, 0.98759566],
       [0.12728511, 0.63082022, 0.27968435, 0.15170706],
       [0.75656545, 0.36671712, 0.48470484, 0.77063809],
       [0.5664136 , 0.94958911, 0.24881782, 0.86153044],
       [0.86952874, 0.84794637, 0.19375415, 0.53742626],
       [0.19211989, 0.97153781, 0.77642878, 0.10081316],
       [0.00119463, 0.1644444 , 0.58747493, 0.2193562 ],
       [0.94050157, 0.75609768, 0.49463837, 0.5539609 ],
       [0.00531412, 0.36728239, 0.56196986, 0.83299955],
       [0.92010958, 0.47535895, 0.66922639, 0.73654857],
       [0.38487041, 0.86929948, 0.74810258, 0.8990612 ],
       [0.91938885, 0.84726248, 0.67815449, 0.79348628],
       [0.09921856, 0.95192768,

In [58]:
X_test  = X[n_train:]
X_test

array([[0.47182389, 0.91254741, 0.45385957, 0.06567155],
       [0.81215726, 0.68368847, 0.73343878, 0.1589456 ],
       [0.35647183, 0.21373642, 0.050725  , 0.91601311],
       [0.35010187, 0.73221626, 0.51083846, 0.52264423],
       [0.81225079, 0.5744336 , 0.13026742, 0.22145901],
       [0.45292282, 0.93346279, 0.46176995, 0.88887429],
       [0.14086056, 0.1566719 , 0.85333469, 0.02830099],
       [0.53135991, 0.84881784, 0.93189724, 0.78437429],
       [0.78292406, 0.79199764, 0.61922327, 0.42845323],
       [0.64845241, 0.95144879, 0.62053906, 0.29398801],
       [0.92614649, 0.40271863, 0.12023296, 0.20014326],
       [0.00521925, 0.49032729, 0.02657775, 0.537648  ],
       [0.48631808, 0.71680439, 0.89142378, 0.2993694 ],
       [0.15166724, 0.57256279, 0.62695987, 0.89732092],
       [0.8483013 , 0.02798728, 0.68879672, 0.51287151],
       [0.14924078, 0.48681411, 0.49200731, 0.661835  ],
       [0.04109288, 0.90345699, 0.54398205, 0.35201104],
       [0.16431809, 0.66470976,

In [59]:
y_train = y[:n_train]
y_train

array([0.06044776, 0.16608517, 0.14012241, 0.99745636, 0.32043724,
       0.70249262, 0.50160136, 0.44907924, 0.59362748, 0.38541508,
       0.90246053, 0.8042335 , 0.09882628, 0.02808579, 0.73717756,
       0.40043016, 0.0444597 , 0.07481363, 0.24774511, 0.31347237,
       0.02975328, 0.94002819, 0.92596296, 0.6487517 , 0.10742356,
       0.57290467, 0.67295034, 0.23569474, 0.74411872, 0.83878979,
       0.01463729, 0.42529004, 0.96334369, 0.42466726, 0.71780542,
       0.67408313, 0.2032687 , 0.27253303, 0.54036294, 0.04965153,
       0.03119883, 0.91582649, 0.38470209, 0.54263418, 0.64443926,
       0.50217294, 0.3844623 , 0.00858315, 0.32119274, 0.08856447,
       0.02328766, 0.01581532, 0.66751799, 0.07335784, 0.6751058 ,
       0.86360722, 0.27768723, 0.9515197 , 0.31684479, 0.65899726,
       0.25527371, 0.63950633, 0.88200833, 0.98668221, 0.33260799,
       0.8137861 , 0.2155823 , 0.21730789, 0.05214014, 0.4467761 ,
       0.12302168, 0.75544703, 0.84859122, 0.2964352 , 0.37731

In [60]:
y_test  = y[n_train:]
y_test

array([0.13483238, 0.78860777, 0.75663165, 0.31880244, 0.00809452,
       0.08285879, 0.20413162, 0.65305834, 0.26282474, 0.33099947,
       0.19633316, 0.62420882, 0.97947957, 0.19855307, 0.24754329,
       0.44660372, 0.02027489, 0.91483189, 0.16001494, 0.43017671,
       0.02143103, 0.92155847, 0.03116266, 0.33113752, 0.8894222 ,
       0.23844169, 0.4631988 , 0.71645598, 0.89360294, 0.18465338,
       0.43318938, 0.88575412, 0.73962459, 0.43401873, 0.28859853,
       0.03584164, 0.01852802, 0.49202007, 0.16885716, 0.55109863,
       0.5682085 , 0.37274964, 0.14951094, 0.02627673, 0.93322875])

In [61]:
X_train_splits = np.array_split(X_train, 10)
X_train_splits

[array([[0.45527071, 0.37045299, 0.05366252, 0.34846423],
        [0.65964803, 0.03495035, 0.79761661, 0.51118292],
        [0.46513476, 0.70792803, 0.08184536, 0.27312753],
        [0.61904487, 0.20865846, 0.57787528, 0.47144522],
        [0.67912254, 0.94414121, 0.41067893, 0.79072892],
        [0.68736667, 0.93316565, 0.31130649, 0.98759566],
        [0.12728511, 0.63082022, 0.27968435, 0.15170706],
        [0.75656545, 0.36671712, 0.48470484, 0.77063809],
        [0.5664136 , 0.94958911, 0.24881782, 0.86153044],
        [0.86952874, 0.84794637, 0.19375415, 0.53742626],
        [0.19211989, 0.97153781, 0.77642878, 0.10081316]]),
 array([[0.00119463, 0.1644444 , 0.58747493, 0.2193562 ],
        [0.94050157, 0.75609768, 0.49463837, 0.5539609 ],
        [0.00531412, 0.36728239, 0.56196986, 0.83299955],
        [0.92010958, 0.47535895, 0.66922639, 0.73654857],
        [0.38487041, 0.86929948, 0.74810258, 0.8990612 ],
        [0.91938885, 0.84726248, 0.67815449, 0.79348628],
        [0.0